# Generated by Django 3.2 on 2024-04-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoringengine', '0022_alter_answer_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('D', 'Date'), ('CH', 'Choices'), ('I', 'Integer'), ('MC', 'Multiple choices'), ('O', 'Open'), ('S', 'Slider')], help_text='<b>Open</b> question without specific expected answer. Has associated value "1" if answer provided and "0" otherwise. Can be used in recommendations rules and in scoring models formulas for X-axis, Y-axis score calculation. </br> <b>Choices</b> question with predefined expected answers options. Answer can be any text. Each answer option has associated value. Can be used in recommendations rules and in scoring models formulas for X-axis, Y-axis score calculation. </br><b>Multiple choices</b> question with predefined expected answers options. Answer can be any text. Multiple answers selection allowed. Each answer option has associated value. Can be used in scoring model for X-axis, Y-axis score calculation but not in recommendations rules and not in scoring models formulas. </br><b>Slider</b> question with predefined range of possible values. Answer is a value. Can be used in recommendations rules and in scoring models formulas for X-axis, Y-axis score calculation. </br>', max_length=2),
        ),
        migrations.CreateModel(
            name='DatesRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, help_text='Left empty for right-closed range', null=True)),
                ('end', models.DateField(blank=True, help_text='Left empty for left-closed range', null=True)),
                ('points', models.IntegerField(help_text='Used for X-axis, Y-axis scores calculation')),
                ('scoring_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_ranges', to='scoringengine.scoringmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datesrange',
            constraint=models.UniqueConstraint(fields=('scoring_model', 'start', 'end'), name='unique_date_range'),
        ),
    ]
