# Generated by Django 3.2 on 2024-06-21 07:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoringengine', '0028_remove_lead_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('y_axis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lead_id', models.UUIDField(default=uuid.uuid4)),
                ('timestamp', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True)),
                ('affiliate_name', models.CharField(blank=True, max_length=200)),
                ('affiliate_image', models.URLField(blank=True, max_length=2048)),
                ('affiliate_link', models.URLField(blank=True, max_length=2048)),
                ('redirect_url', models.URLField(blank=True, max_length=2048)),
                ('field_name', models.CharField(max_length=200)),
                ('response', models.CharField(blank=True, max_length=200)),
                ('value_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True), null=True, size=None)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='scoringengine.leadlog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
