version: '3'

volumes:
  scoringengine_local_postgres_data: {}
  scoringengine_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: scoringengine_local_django
    container_name: scoringengine_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: scoringengine_local_postgres
    container_name: scoringengine_local_postgres
    volumes:
      - scoringengine_local_postgres_data:/var/lib/postgresql/data:Z
      - scoringengine_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
