# Generated by Django 3.2 on 2021-06-01 11:52
import re

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Update default value for existing questions
    Choice = apps.get_model("scoringengine", "Choice")
    db_alias = schema_editor.connection.alias

    choices = Choice.objects.using(db_alias).all()

    for choice in choices:
        choice.value = max([int(w) for w in re.findall(r"\d+", choice.text)])
        choice.save()


def reverse_func(apps, schema_editor):
    # No need to reverse to default values
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0002_auto_20210601_1247"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
