# Generated by Django 3.2 on 2021-06-01 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringengine', '0003_set_choice_values_for_existing_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='<b>Note:</b> Used only for question with choices', max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='x_axis',
            field=models.BooleanField(help_text='<b>Note:</b> Used only for question with choices'),
        ),
        migrations.AlterField(
            model_name='question',
            name='y_axis',
            field=models.BooleanField(help_text='<b>Note:</b> Used only for question with choices'),
        ),
    ]
