# Generated by Django 3.2 on 2021-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0005_alter_rule_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="choice",
            name="points",
            field=models.IntegerField(
                help_text="Used for X-axis, Y-axis scores calculation"
            ),
        ),
    ]
