# Generated by Django 3.2 on 2021-06-29 15:26

from django.db import migrations
from django.template.defaultfilters import slugify


def forwards_func(apps, schema_editor):
    # Update default value for existing questions
    Choice = apps.get_model("scoringengine", "Choice")
    db_alias = schema_editor.connection.alias

    choices = Choice.objects.using(db_alias).all()

    for choice in choices:
        choice.slug = slugify(choice.text)
        choice.save()


def reverse_func(apps, schema_editor):
    # No need to reverse to default values
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0006_auto_20210629_1526"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
