# Generated by Django 3.2 on 2021-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0007_set_slug_for_existing_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                fields=("question", "slug"), name="unique_slug"
            ),
        ),
    ]
