# Generated by Django 3.2 on 2021-07-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoringengine', '0009_rename_rule_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='scoringengine.question'),
        ),
    ]
