# Generated by Django 3.2 on 2021-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringengine', '0010_auto_20210702_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('O', 'Open'), ('CH', 'Choices'), ('S', 'Slider')], default='CH', help_text='<b>Open</b> questions without specific expected answer. Has no associated value and points, so can not be used in recommendation rules and for X-axis, Y-axis score calculation. </br> <b>Choices</b> question with predefined expected answers options. Answer can be any text. Each answer option has associated value and points. Can be used in recommendation rules and for X-axis, Y-axis score calculation. </br><b>Slider</b> question with predefined range of possible values. Answer is a value.Sub-ranges of value have associated points. Can be used in recommendation rules and for X-axis, Y-axis score calculation. </br>', max_length=2),
            preserve_default=False,
        ),
    ]
