# Generated by Django 3.2 on 2022-02-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0017_auto_20211108_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="response_text",
            field=models.TextField(blank=True),
        ),
    ]
