# Generated by Django 3.2 on 2022-02-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringengine', '0020_calculate_total_score_retrospectively'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
