# Generated by Django 3.2 on 2022-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0021_alter_lead_total_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="response_text",
            field=models.TextField(blank=True),
        ),
    ]
