# Generated by Django 3.2 on 2024-05-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoringengine', '0027_lead_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
    ]
