# Generated by Django 3.2 on 2024-07-19 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalogue_as_master', serialize=False, to='auth.user', verbose_name='Master user')),
                ('slaves', models.ManyToManyField(blank=True, related_name='catalogues_as_slave', to=settings.AUTH_USER_MODEL, verbose_name='Slaves user')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
            },
        ),
    ]
