# Generated by Django 3.2 on 2021-07-01 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scoringengine", "0008_auto_20210629_1528"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rule",
            new_name="Recommendation",
        ),
    ]
