# Generated by Django 3.2 on 2021-07-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0013_migrate_questions_to_scoring_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="points",
        ),
        migrations.RemoveField(
            model_name="question",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="question",
            name="x_axis",
        ),
        migrations.RemoveField(
            model_name="question",
            name="y_axis",
        ),
    ]
