# Generated by Django 3.2 on 2024-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0023_auto_20240403_0855"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique_answer",
        ),
        migrations.AddField(
            model_name="answer",
            name="value_number",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="multiple_values",
            field=models.BooleanField(default=False),
        ),
    ]
