# Generated by Django 3.2 on 2024-05-11 14:59

from django.db import migrations, models

import scoringengine.models


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0025_auto_20240509_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="rule",
            field=models.CharField(
                help_text='Rule should start with "If" and may contain only valid numbers, questions with choices "Field names" in curly braces (e.g. {field_name}) combined with arithmetic (+, -, *, %, /, **, //), comparison (>, <, ==, !=, >=, <=), logical operations (and, or, not) and parentheses to select points based on expression result.</br>Aggregate functions which may be used in are: count, max, mean, median, min, sum</br>Mathematical functions which may be used in are: sqrt</br>Date functions which may be used in are: days, today',
                max_length=500,
                validators=[scoringengine.models.validate_rule],
            ),
        ),
        migrations.AlterField(
            model_name="scoringmodel",
            name="formula",
            field=models.CharField(
                blank=True,
                help_text='Leave empty to select points based on direct value from associated question.</br>Add expression with "Field names" in curly braces (e.g. {field_name}), arithmetic (+, -, *, %, /, **, //) operations and parentheses to select points based on expression result.</br>Aggregate functions which may be used in are: count, max, mean, median, min, sum</br>Mathematical functions which may be used in are: sqrt</br>Date functions which may be used in are: days, today',
                max_length=500,
                validators=[scoringengine.models.validate_formula],
            ),
        ),
    ]
