# Generated by Django 3.2 on 2024-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoringengine", "0026_auto_20240511_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
